import Head from "next/head";
import Navbar from "../components/Navbar";
import Home from "../components/home/Home";
import About from "../components/about/About";
import Projects from "../components/proyects/Projects";

const Principal = () => {
  return (
    <>
      <Head>
        <title>Alfonso</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../public/ja.ico" />
      </Head>
      <div>
        <Navbar />
        <section
          id="start"
          className=" text-zinc-200 text-center flex flex-wrap justify-center items-center"
        >
          <Home />
        </section>
        <section
          id="about"
          className=" text-zinc-200 h-screen flex flex-wrap justify-center items-center bg-marine"
        >
          <About />
        </section>
        <section
          id="projects"
          className="text-zinc-200 h-screen text-center flex flex-wrap justify-center items-center bg-marine"
        >
          <Projects />
        </section>
        <section id="techs" className=" text-zinc-200 h-screen flex bg-marine">
          <h1 className="m-auto text-7xl text-zinc-200 font-bold">
            Tecnologías
          </h1>
        </section>
        <section
          id="contact"
          className=" text-zinc-200 h-screen flex bg-marine"
        >
          <h1 className="m-auto text-7xl text-zinc-200 font-bold">Contacto</h1>
        </section>
      </div>
    </>
  );
};

export default Principal;
