import Head from "next/head";
import Navbar from "../components/Navbar";
import Home from "../components/home/Home";
import About from "../components/about/About";
import Projects from "../components/projects/Projects";
import Techs from "../components/techs/Techs";
import Contact from "../components/contact/Contact";

const Principal = () => {
  return (
    <>
      <Head>
        <title>Alfonso</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../public/ja.ico" />
      </Head>
      <div>
        <Navbar />
        <section
          id="start"
          className=" text-zinc-200 text-center flex flex-wrap justify-center items-center"
        >
          <Home />
        </section>
        <section
          id="about"
          className=" text-zinc-200 h-screen flex flex-wrap justify-center items-center bg-marine"
        >
          <About />
        </section>
        <section
          id="projects"
          className="pt-16 text-zinc-200 h-screen text-center flex flex-wrap justify-center items-center bg-marine"
        >
          <h1 className="pt-12 text-4xl font-bold text-zinc-100 md:px-6 text-center">
            Mi portafolio
          </h1>
          <Projects />
        </section>
        <section className=" text-zinc-200 h-screen flex flex-wrap justify-center items-center bg-marine"></section>
        <section
          id="techs"
          className=" text-zinc-200 h-screen flex flex-wrap justify-center items-center bg-marine"
        >
          <h1 className="pt-28 text-4xl font-bold text-zinc-100 md:px-6 text-center">
            Tecnologías que práctico
          </h1>
          <Techs />
        </section>
        <section
          id="contact"
          className=" text-zinc-200 h-screen flex flex-wrap justify-center items-center bg-marine"
        >
          <Contact />
        </section>
      </div>
    </>
  );
};

export default Principal;
